export default {
  items: [
    {
      id: 44431578,
      num_sales: 0,
      background_color: null,
      image_url:
        "https://lh3.googleusercontent.com/DgcqDdBBe608boHPyXEjw2h-Qf4U0Ul3jsdayZRcpGLOUCl_VFgoJ0E3tQmrQ0ZrOg3UQWgIGMaJ1h9eoxkqUcR8IvvyzGQUlJQEgg",
      image_preview_url:
        "https://lh3.googleusercontent.com/DgcqDdBBe608boHPyXEjw2h-Qf4U0Ul3jsdayZRcpGLOUCl_VFgoJ0E3tQmrQ0ZrOg3UQWgIGMaJ1h9eoxkqUcR8IvvyzGQUlJQEgg=s250",
      image_thumbnail_url:
        "https://lh3.googleusercontent.com/DgcqDdBBe608boHPyXEjw2h-Qf4U0Ul3jsdayZRcpGLOUCl_VFgoJ0E3tQmrQ0ZrOg3UQWgIGMaJ1h9eoxkqUcR8IvvyzGQUlJQEgg=s128",
      image_original_url:
        "ipfs://QmZs1gr9b89sv8KQQbcXUvAHpZ86uHrBJLB7HaoGsLbyec/0.png",
      animation_url: null,
      animation_original_url: null,
      name: "Samurai Moody",
      description: null,
      external_link: null,
      asset_contract: {
        address: "0xe3701f48a27f5868886fe6b04f914dd8d213294a",
        asset_contract_type: "non-fungible",
        created_date: "2022-02-23T18:43:40.513860",
        name: "Cryptopunks Clone",
        nft_version: "3.0",
        opensea_version: null,
        owner: 6113398,
        schema_name: "ERC721",
        symbol: "CP Clone",
        total_supply: "0",
        description: "",
        external_link: null,
        image_url:
          "https://lh3.googleusercontent.com/bPA4J9E5nVJkcDfiD0h8ajXhR_wbsPNz_r_AK--QzT5dT5Ij4EWTdXJk_boA9u3eBg1eI7vA8w8sWhRST8tTXboi5SqxBpdcoliyew=s120",
        default_to_fiat: false,
        dev_buyer_fee_basis_points: 0,
        dev_seller_fee_basis_points: 0,
        only_proxied_transfers: false,
        opensea_buyer_fee_basis_points: 0,
        opensea_seller_fee_basis_points: 250,
        buyer_fee_basis_points: 0,
        seller_fee_basis_points: 250,
        payout_address: "0xb43dfed270a0d9b637d114e237a3db9bc8ee59eb",
      },
      permalink:
        "https://testnets.opensea.io/assets/0xe3701f48a27f5868886fe6b04f914dd8d213294a/5",
      collection: {
        banner_image_url: null,
        chat_url: null,
        created_date: "2022-02-23T18:51:12.759193",
        default_to_fiat: false,
        description: "",
        dev_buyer_fee_basis_points: "0",
        dev_seller_fee_basis_points: "0",
        discord_url: null,
        display_data: {
          card_display_style: "contain",
          images: [],
        },
        external_url: null,
        featured: false,
        featured_image_url: null,
        hidden: false,
        safelist_request_status: "not_requested",
        image_url:
          "https://lh3.googleusercontent.com/bPA4J9E5nVJkcDfiD0h8ajXhR_wbsPNz_r_AK--QzT5dT5Ij4EWTdXJk_boA9u3eBg1eI7vA8w8sWhRST8tTXboi5SqxBpdcoliyew=s120",
        is_subject_to_whitelist: false,
        large_image_url:
          "https://lh3.googleusercontent.com/bPA4J9E5nVJkcDfiD0h8ajXhR_wbsPNz_r_AK--QzT5dT5Ij4EWTdXJk_boA9u3eBg1eI7vA8w8sWhRST8tTXboi5SqxBpdcoliyew",
        medium_username: null,
        name: "Cryptopunks Clone - zxNnyUKh8r",
        only_proxied_transfers: false,
        opensea_buyer_fee_basis_points: "0",
        opensea_seller_fee_basis_points: "250",
        payout_address: "0xb43dfed270a0d9b637d114e237a3db9bc8ee59eb",
        require_email: false,
        short_description: null,
        slug: "cryptopunks-clone-zxnnyukh8r",
        telegram_url: null,
        twitter_username: null,
        instagram_username: null,
        wiki_url: null,
      },
      decimals: 0,
      token_metadata:
        "https://opensea.mypinata.cloud/ipfs/QmSCmcMjM2qoxCDfhRjmWpaxkVYrF6CXiGZgZxGG6hWb8K/0",
      owner: {
        user: null,
        profile_img_url:
          "https://storage.googleapis.com/opensea-static/opensea-profile/3.png",
        address: "0x2273beee08c7362ea9df7f5b22b6d43c0d2afccb",
        config: "",
      },
      sell_orders: null,
      creator: null,
      traits: [
        {
          trait_type: "price",
          value: "16",
          display_type: null,
          max_value: null,
          trait_count: 1,
          order: null,
        },
      ],
      last_sale: null,
      top_bid: null,
      listing_date: null,
      is_presale: false,
      transfer_fee_payment_token: null,
      transfer_fee: null,
      token_id: "5",
    },
    {
      id: 44430752,
      num_sales: 0,
      background_color: null,
      image_url:
        "https://lh3.googleusercontent.com/tQxY41Do9CWKaSwYEh6qtMaUfxDqPD5noifrh5j2XJqGUMyLH8WFIdq1NzAhYAhIiiPVAuEd3IMSHLPdFptCtDyemh78rBEIM_UM0w",
      image_preview_url:
        "https://lh3.googleusercontent.com/tQxY41Do9CWKaSwYEh6qtMaUfxDqPD5noifrh5j2XJqGUMyLH8WFIdq1NzAhYAhIiiPVAuEd3IMSHLPdFptCtDyemh78rBEIM_UM0w=s250",
      image_thumbnail_url:
        "https://lh3.googleusercontent.com/tQxY41Do9CWKaSwYEh6qtMaUfxDqPD5noifrh5j2XJqGUMyLH8WFIdq1NzAhYAhIiiPVAuEd3IMSHLPdFptCtDyemh78rBEIM_UM0w=s128",
      image_original_url:
        "ipfs://QmZ2X9s2HnWGBuU7z2dET1DqGZ4xuyqG1dWJYkRWcyP2sB/0.jpg",
      animation_url: null,
      animation_original_url: null,
      name: "Laser Moody",
      description: null,
      external_link: null,
      asset_contract: {
        address: "0xe3701f48a27f5868886fe6b04f914dd8d213294a",
        asset_contract_type: "non-fungible",
        created_date: "2022-02-23T18:43:40.513860",
        name: "Cryptopunks Clone",
        nft_version: "3.0",
        opensea_version: null,
        owner: 6113398,
        schema_name: "ERC721",
        symbol: "CP Clone",
        total_supply: "0",
        description: "",
        external_link: null,
        image_url:
          "https://lh3.googleusercontent.com/bPA4J9E5nVJkcDfiD0h8ajXhR_wbsPNz_r_AK--QzT5dT5Ij4EWTdXJk_boA9u3eBg1eI7vA8w8sWhRST8tTXboi5SqxBpdcoliyew=s120",
        default_to_fiat: false,
        dev_buyer_fee_basis_points: 0,
        dev_seller_fee_basis_points: 0,
        only_proxied_transfers: false,
        opensea_buyer_fee_basis_points: 0,
        opensea_seller_fee_basis_points: 250,
        buyer_fee_basis_points: 0,
        seller_fee_basis_points: 250,
        payout_address: "0xb43dfed270a0d9b637d114e237a3db9bc8ee59eb",
      },
      permalink:
        "https://testnets.opensea.io/assets/0xe3701f48a27f5868886fe6b04f914dd8d213294a/4",
      collection: {
        banner_image_url: null,
        chat_url: null,
        created_date: "2022-02-23T18:51:12.759193",
        default_to_fiat: false,
        description: "",
        dev_buyer_fee_basis_points: "0",
        dev_seller_fee_basis_points: "0",
        discord_url: null,
        display_data: {
          card_display_style: "contain",
          images: [],
        },
        external_url: null,
        featured: false,
        featured_image_url: null,
        hidden: false,
        safelist_request_status: "not_requested",
        image_url:
          "https://lh3.googleusercontent.com/bPA4J9E5nVJkcDfiD0h8ajXhR_wbsPNz_r_AK--QzT5dT5Ij4EWTdXJk_boA9u3eBg1eI7vA8w8sWhRST8tTXboi5SqxBpdcoliyew=s120",
        is_subject_to_whitelist: false,
        large_image_url:
          "https://lh3.googleusercontent.com/bPA4J9E5nVJkcDfiD0h8ajXhR_wbsPNz_r_AK--QzT5dT5Ij4EWTdXJk_boA9u3eBg1eI7vA8w8sWhRST8tTXboi5SqxBpdcoliyew",
        medium_username: null,
        name: "Cryptopunks Clone - zxNnyUKh8r",
        only_proxied_transfers: false,
        opensea_buyer_fee_basis_points: "0",
        opensea_seller_fee_basis_points: "250",
        payout_address: "0xb43dfed270a0d9b637d114e237a3db9bc8ee59eb",
        require_email: false,
        short_description: null,
        slug: "cryptopunks-clone-zxnnyukh8r",
        telegram_url: null,
        twitter_username: null,
        instagram_username: null,
        wiki_url: null,
      },
      decimals: 0,
      token_metadata:
        "https://opensea.mypinata.cloud/ipfs/QmPmfuXRvkdmLGSQh9hy81nGq9qzDsprU6MEJNVbArw5vN/0",
      owner: {
        user: null,
        profile_img_url:
          "https://storage.googleapis.com/opensea-static/opensea-profile/3.png",
        address: "0x2273beee08c7362ea9df7f5b22b6d43c0d2afccb",
        config: "",
      },
      sell_orders: null,
      creator: null,
      traits: [
        {
          trait_type: "price",
          value: "17",
          display_type: null,
          max_value: null,
          trait_count: 1,
          order: null,
        },
      ],
      last_sale: null,
      top_bid: null,
      listing_date: null,
      is_presale: false,
      transfer_fee_payment_token: null,
      transfer_fee: null,
      token_id: "4",
    },
    {
      id: 44430183,
      num_sales: 0,
      background_color: null,
      image_url:
        "https://lh3.googleusercontent.com/6-MJYxq0DNWGZ_K7PzvomVAkOjmiVb2OPhQyl2-Sh3DjjHiIzYFECINsuyPwlmfVI2wbaSYPo7V6mFl2o6tQr50ZG4Uec51pACX1",
      image_preview_url:
        "https://lh3.googleusercontent.com/6-MJYxq0DNWGZ_K7PzvomVAkOjmiVb2OPhQyl2-Sh3DjjHiIzYFECINsuyPwlmfVI2wbaSYPo7V6mFl2o6tQr50ZG4Uec51pACX1=s250",
      image_thumbnail_url:
        "https://lh3.googleusercontent.com/6-MJYxq0DNWGZ_K7PzvomVAkOjmiVb2OPhQyl2-Sh3DjjHiIzYFECINsuyPwlmfVI2wbaSYPo7V6mFl2o6tQr50ZG4Uec51pACX1=s128",
      image_original_url:
        "ipfs://QmaUABitxdzpWurb4RKtw4Be9YPZvufNseUfFuL7wTC9KE/0.png",
      animation_url: null,
      animation_original_url: null,
      name: "Mcdonalds Moody",
      description: null,
      external_link: null,
      asset_contract: {
        address: "0xe3701f48a27f5868886fe6b04f914dd8d213294a",
        asset_contract_type: "non-fungible",
        created_date: "2022-02-23T18:43:40.513860",
        name: "Cryptopunks Clone",
        nft_version: "3.0",
        opensea_version: null,
        owner: 6113398,
        schema_name: "ERC721",
        symbol: "CP Clone",
        total_supply: "0",
        description: "",
        external_link: null,
        image_url:
          "https://lh3.googleusercontent.com/bPA4J9E5nVJkcDfiD0h8ajXhR_wbsPNz_r_AK--QzT5dT5Ij4EWTdXJk_boA9u3eBg1eI7vA8w8sWhRST8tTXboi5SqxBpdcoliyew=s120",
        default_to_fiat: false,
        dev_buyer_fee_basis_points: 0,
        dev_seller_fee_basis_points: 0,
        only_proxied_transfers: false,
        opensea_buyer_fee_basis_points: 0,
        opensea_seller_fee_basis_points: 250,
        buyer_fee_basis_points: 0,
        seller_fee_basis_points: 250,
        payout_address: "0xb43dfed270a0d9b637d114e237a3db9bc8ee59eb",
      },
      permalink:
        "https://testnets.opensea.io/assets/0xe3701f48a27f5868886fe6b04f914dd8d213294a/3",
      collection: {
        banner_image_url: null,
        chat_url: null,
        created_date: "2022-02-23T18:51:12.759193",
        default_to_fiat: false,
        description: "",
        dev_buyer_fee_basis_points: "0",
        dev_seller_fee_basis_points: "0",
        discord_url: null,
        display_data: {
          card_display_style: "contain",
          images: [],
        },
        external_url: null,
        featured: false,
        featured_image_url: null,
        hidden: false,
        safelist_request_status: "not_requested",
        image_url:
          "https://lh3.googleusercontent.com/bPA4J9E5nVJkcDfiD0h8ajXhR_wbsPNz_r_AK--QzT5dT5Ij4EWTdXJk_boA9u3eBg1eI7vA8w8sWhRST8tTXboi5SqxBpdcoliyew=s120",
        is_subject_to_whitelist: false,
        large_image_url:
          "https://lh3.googleusercontent.com/bPA4J9E5nVJkcDfiD0h8ajXhR_wbsPNz_r_AK--QzT5dT5Ij4EWTdXJk_boA9u3eBg1eI7vA8w8sWhRST8tTXboi5SqxBpdcoliyew",
        medium_username: null,
        name: "Cryptopunks Clone - zxNnyUKh8r",
        only_proxied_transfers: false,
        opensea_buyer_fee_basis_points: "0",
        opensea_seller_fee_basis_points: "250",
        payout_address: "0xb43dfed270a0d9b637d114e237a3db9bc8ee59eb",
        require_email: false,
        short_description: null,
        slug: "cryptopunks-clone-zxnnyukh8r",
        telegram_url: null,
        twitter_username: null,
        instagram_username: null,
        wiki_url: null,
      },
      decimals: 0,
      token_metadata:
        "https://opensea.mypinata.cloud/ipfs/QmSHhkDhWE4TggQrzBQvDjrUQtfdS41Kz8XHtya4XDcy3K/0",
      owner: {
        user: null,
        profile_img_url:
          "https://storage.googleapis.com/opensea-static/opensea-profile/3.png",
        address: "0x2273beee08c7362ea9df7f5b22b6d43c0d2afccb",
        config: "",
      },
      sell_orders: null,
      creator: null,
      traits: [
        {
          trait_type: "price",
          value: "10",
          display_type: null,
          max_value: null,
          trait_count: 1,
          order: null,
        },
      ],
      last_sale: null,
      top_bid: null,
      listing_date: null,
      is_presale: false,
      transfer_fee_payment_token: null,
      transfer_fee: null,
      token_id: "3",
    },
    {
      id: 44430052,
      num_sales: 0,
      background_color: null,
      image_url:
        "https://lh3.googleusercontent.com/XlenBwuuFEBlZj3xiOwgykU6C-EFqJx_0WXB6bz6jZL6XFItX4bLOBgEsiydWhHbqbuX8FPKojHVINm8nlUHmjjl5FrXLgs7rv1Obg",
      image_preview_url:
        "https://lh3.googleusercontent.com/XlenBwuuFEBlZj3xiOwgykU6C-EFqJx_0WXB6bz6jZL6XFItX4bLOBgEsiydWhHbqbuX8FPKojHVINm8nlUHmjjl5FrXLgs7rv1Obg=s250",
      image_thumbnail_url:
        "https://lh3.googleusercontent.com/XlenBwuuFEBlZj3xiOwgykU6C-EFqJx_0WXB6bz6jZL6XFItX4bLOBgEsiydWhHbqbuX8FPKojHVINm8nlUHmjjl5FrXLgs7rv1Obg=s128",
      image_original_url:
        "ipfs://QmPPBURxhe2Uii74eXYdRC6a5cmEDn6AJf5TYPJJknwFuT/0.png",
      animation_url: null,
      animation_original_url: null,
      name: "Albinos Moody",
      description: null,
      external_link: null,
      asset_contract: {
        address: "0xe3701f48a27f5868886fe6b04f914dd8d213294a",
        asset_contract_type: "non-fungible",
        created_date: "2022-02-23T18:43:40.513860",
        name: "Cryptopunks Clone",
        nft_version: "3.0",
        opensea_version: null,
        owner: 6113398,
        schema_name: "ERC721",
        symbol: "CP Clone",
        total_supply: "0",
        description: "",
        external_link: null,
        image_url:
          "https://lh3.googleusercontent.com/bPA4J9E5nVJkcDfiD0h8ajXhR_wbsPNz_r_AK--QzT5dT5Ij4EWTdXJk_boA9u3eBg1eI7vA8w8sWhRST8tTXboi5SqxBpdcoliyew=s120",
        default_to_fiat: false,
        dev_buyer_fee_basis_points: 0,
        dev_seller_fee_basis_points: 0,
        only_proxied_transfers: false,
        opensea_buyer_fee_basis_points: 0,
        opensea_seller_fee_basis_points: 250,
        buyer_fee_basis_points: 0,
        seller_fee_basis_points: 250,
        payout_address: "0xb43dfed270a0d9b637d114e237a3db9bc8ee59eb",
      },
      permalink:
        "https://testnets.opensea.io/assets/0xe3701f48a27f5868886fe6b04f914dd8d213294a/2",
      collection: {
        banner_image_url: null,
        chat_url: null,
        created_date: "2022-02-23T18:51:12.759193",
        default_to_fiat: false,
        description: "",
        dev_buyer_fee_basis_points: "0",
        dev_seller_fee_basis_points: "0",
        discord_url: null,
        display_data: {
          card_display_style: "contain",
          images: [],
        },
        external_url: null,
        featured: false,
        featured_image_url: null,
        hidden: false,
        safelist_request_status: "not_requested",
        image_url:
          "https://lh3.googleusercontent.com/bPA4J9E5nVJkcDfiD0h8ajXhR_wbsPNz_r_AK--QzT5dT5Ij4EWTdXJk_boA9u3eBg1eI7vA8w8sWhRST8tTXboi5SqxBpdcoliyew=s120",
        is_subject_to_whitelist: false,
        large_image_url:
          "https://lh3.googleusercontent.com/bPA4J9E5nVJkcDfiD0h8ajXhR_wbsPNz_r_AK--QzT5dT5Ij4EWTdXJk_boA9u3eBg1eI7vA8w8sWhRST8tTXboi5SqxBpdcoliyew",
        medium_username: null,
        name: "Cryptopunks Clone - zxNnyUKh8r",
        only_proxied_transfers: false,
        opensea_buyer_fee_basis_points: "0",
        opensea_seller_fee_basis_points: "250",
        payout_address: "0xb43dfed270a0d9b637d114e237a3db9bc8ee59eb",
        require_email: false,
        short_description: null,
        slug: "cryptopunks-clone-zxnnyukh8r",
        telegram_url: null,
        twitter_username: null,
        instagram_username: null,
        wiki_url: null,
      },
      decimals: 0,
      token_metadata:
        "https://opensea.mypinata.cloud/ipfs/QmToobTwEEC3kbf6EUhMwN7ccWrCVJrLwMCr2PndbdoXwC/0",
      owner: {
        user: null,
        profile_img_url:
          "https://storage.googleapis.com/opensea-static/opensea-profile/3.png",
        address: "0x2273beee08c7362ea9df7f5b22b6d43c0d2afccb",
        config: "",
      },
      sell_orders: null,
      creator: null,
      traits: [
        {
          trait_type: "price",
          value: "24",
          display_type: null,
          max_value: null,
          trait_count: 1,
          order: null,
        },
      ],
      last_sale: null,
      top_bid: null,
      listing_date: null,
      is_presale: false,
      transfer_fee_payment_token: null,
      transfer_fee: null,
      token_id: "2",
    },
    {
      id: 44429606,
      num_sales: 0,
      background_color: null,
      image_url:
        "https://lh3.googleusercontent.com/sxCecfmeWBE6tRr2edfr2HsxR8nZsi7RCgCIiJNaNkiyriJlTB4zSDn14Hhj-BVE6hii27NoDKjwEy_W09VEtaN_62tpckt4ayGjSA",
      image_preview_url:
        "https://lh3.googleusercontent.com/sxCecfmeWBE6tRr2edfr2HsxR8nZsi7RCgCIiJNaNkiyriJlTB4zSDn14Hhj-BVE6hii27NoDKjwEy_W09VEtaN_62tpckt4ayGjSA=s250",
      image_thumbnail_url:
        "https://lh3.googleusercontent.com/sxCecfmeWBE6tRr2edfr2HsxR8nZsi7RCgCIiJNaNkiyriJlTB4zSDn14Hhj-BVE6hii27NoDKjwEy_W09VEtaN_62tpckt4ayGjSA=s128",
      image_original_url:
        "ipfs://QmTweyAwDofJrsmbs2eqHw5YUExDhZtXMEojkkv5UVtzS9/0.png",
      animation_url: null,
      animation_original_url: null,
      name: "Basketball Moody",
      description: null,
      external_link: null,
      asset_contract: {
        address: "0xe3701f48a27f5868886fe6b04f914dd8d213294a",
        asset_contract_type: "non-fungible",
        created_date: "2022-02-23T18:43:40.513860",
        name: "Cryptopunks Clone",
        nft_version: "3.0",
        opensea_version: null,
        owner: 6113398,
        schema_name: "ERC721",
        symbol: "CP Clone",
        total_supply: "0",
        description: "",
        external_link: null,
        image_url:
          "https://lh3.googleusercontent.com/bPA4J9E5nVJkcDfiD0h8ajXhR_wbsPNz_r_AK--QzT5dT5Ij4EWTdXJk_boA9u3eBg1eI7vA8w8sWhRST8tTXboi5SqxBpdcoliyew=s120",
        default_to_fiat: false,
        dev_buyer_fee_basis_points: 0,
        dev_seller_fee_basis_points: 0,
        only_proxied_transfers: false,
        opensea_buyer_fee_basis_points: 0,
        opensea_seller_fee_basis_points: 250,
        buyer_fee_basis_points: 0,
        seller_fee_basis_points: 250,
        payout_address: "0xb43dfed270a0d9b637d114e237a3db9bc8ee59eb",
      },
      permalink:
        "https://testnets.opensea.io/assets/0xe3701f48a27f5868886fe6b04f914dd8d213294a/1",
      collection: {
        banner_image_url: null,
        chat_url: null,
        created_date: "2022-02-23T18:51:12.759193",
        default_to_fiat: false,
        description: "",
        dev_buyer_fee_basis_points: "0",
        dev_seller_fee_basis_points: "0",
        discord_url: null,
        display_data: {
          card_display_style: "contain",
          images: [],
        },
        external_url: null,
        featured: false,
        featured_image_url: null,
        hidden: false,
        safelist_request_status: "not_requested",
        image_url:
          "https://lh3.googleusercontent.com/bPA4J9E5nVJkcDfiD0h8ajXhR_wbsPNz_r_AK--QzT5dT5Ij4EWTdXJk_boA9u3eBg1eI7vA8w8sWhRST8tTXboi5SqxBpdcoliyew=s120",
        is_subject_to_whitelist: false,
        large_image_url:
          "https://lh3.googleusercontent.com/bPA4J9E5nVJkcDfiD0h8ajXhR_wbsPNz_r_AK--QzT5dT5Ij4EWTdXJk_boA9u3eBg1eI7vA8w8sWhRST8tTXboi5SqxBpdcoliyew",
        medium_username: null,
        name: "Cryptopunks Clone - zxNnyUKh8r",
        only_proxied_transfers: false,
        opensea_buyer_fee_basis_points: "0",
        opensea_seller_fee_basis_points: "250",
        payout_address: "0xb43dfed270a0d9b637d114e237a3db9bc8ee59eb",
        require_email: false,
        short_description: null,
        slug: "cryptopunks-clone-zxnnyukh8r",
        telegram_url: null,
        twitter_username: null,
        instagram_username: null,
        wiki_url: null,
      },
      decimals: 0,
      token_metadata:
        "https://opensea.mypinata.cloud/ipfs/QmSAVWJj4GijtndrQEJLKSE696X5npsY5seKbavQDSJhpX/0",
      owner: {
        user: null,
        profile_img_url:
          "https://storage.googleapis.com/opensea-static/opensea-profile/3.png",
        address: "0x2273beee08c7362ea9df7f5b22b6d43c0d2afccb",
        config: "",
      },
      sell_orders: null,
      creator: null,
      traits: [
        {
          trait_type: "price",
          value: "12",
          display_type: null,
          max_value: null,
          trait_count: 1,
          order: null,
        },
      ],
      last_sale: null,
      top_bid: null,
      listing_date: null,
      is_presale: false,
      transfer_fee_payment_token: null,
      transfer_fee: null,
      token_id: "1",
    },
    {
      id: 44428979,
      num_sales: 0,
      background_color: null,
      image_url:
        "https://lh3.googleusercontent.com/cw9KryPIAX-lKvDmcL1sMSYwDZacGI790XzaRcuOHzbsratb3vx2gE2MexR7GZiaZMijAarXHm_XOekWGTVrvi0tqw9T7v0XO5tKIZg",
      image_preview_url:
        "https://lh3.googleusercontent.com/cw9KryPIAX-lKvDmcL1sMSYwDZacGI790XzaRcuOHzbsratb3vx2gE2MexR7GZiaZMijAarXHm_XOekWGTVrvi0tqw9T7v0XO5tKIZg=s250",
      image_thumbnail_url:
        "https://lh3.googleusercontent.com/cw9KryPIAX-lKvDmcL1sMSYwDZacGI790XzaRcuOHzbsratb3vx2gE2MexR7GZiaZMijAarXHm_XOekWGTVrvi0tqw9T7v0XO5tKIZg=s128",
      image_original_url:
        "ipfs://QmS8DKmmhhpSNhK6ZXR8GngwWsGpPVvtX9gh3hjr9R7SLQ/0.png",
      animation_url: null,
      animation_original_url: null,
      name: "Dark Moody",
      description: null,
      external_link: null,
      asset_contract: {
        address: "0xe3701f48a27f5868886fe6b04f914dd8d213294a",
        asset_contract_type: "non-fungible",
        created_date: "2022-02-23T18:43:40.513860",
        name: "Cryptopunks Clone",
        nft_version: "3.0",
        opensea_version: null,
        owner: 6113398,
        schema_name: "ERC721",
        symbol: "CP Clone",
        total_supply: "0",
        description: "",
        external_link: null,
        image_url:
          "https://lh3.googleusercontent.com/bPA4J9E5nVJkcDfiD0h8ajXhR_wbsPNz_r_AK--QzT5dT5Ij4EWTdXJk_boA9u3eBg1eI7vA8w8sWhRST8tTXboi5SqxBpdcoliyew=s120",
        default_to_fiat: false,
        dev_buyer_fee_basis_points: 0,
        dev_seller_fee_basis_points: 0,
        only_proxied_transfers: false,
        opensea_buyer_fee_basis_points: 0,
        opensea_seller_fee_basis_points: 250,
        buyer_fee_basis_points: 0,
        seller_fee_basis_points: 250,
        payout_address: "0xb43dfed270a0d9b637d114e237a3db9bc8ee59eb",
      },
      permalink:
        "https://testnets.opensea.io/assets/0xe3701f48a27f5868886fe6b04f914dd8d213294a/0",
      collection: {
        banner_image_url: null,
        chat_url: null,
        created_date: "2022-02-23T18:51:12.759193",
        default_to_fiat: false,
        description: "",
        dev_buyer_fee_basis_points: "0",
        dev_seller_fee_basis_points: "0",
        discord_url: null,
        display_data: {
          card_display_style: "contain",
          images: [],
        },
        external_url: null,
        featured: false,
        featured_image_url: null,
        hidden: false,
        safelist_request_status: "not_requested",
        image_url:
          "https://lh3.googleusercontent.com/bPA4J9E5nVJkcDfiD0h8ajXhR_wbsPNz_r_AK--QzT5dT5Ij4EWTdXJk_boA9u3eBg1eI7vA8w8sWhRST8tTXboi5SqxBpdcoliyew=s120",
        is_subject_to_whitelist: false,
        large_image_url:
          "https://lh3.googleusercontent.com/bPA4J9E5nVJkcDfiD0h8ajXhR_wbsPNz_r_AK--QzT5dT5Ij4EWTdXJk_boA9u3eBg1eI7vA8w8sWhRST8tTXboi5SqxBpdcoliyew",
        medium_username: null,
        name: "Cryptopunks Clone - zxNnyUKh8r",
        only_proxied_transfers: false,
        opensea_buyer_fee_basis_points: "0",
        opensea_seller_fee_basis_points: "250",
        payout_address: "0xb43dfed270a0d9b637d114e237a3db9bc8ee59eb",
        require_email: false,
        short_description: null,
        slug: "cryptopunks-clone-zxnnyukh8r",
        telegram_url: null,
        twitter_username: null,
        instagram_username: null,
        wiki_url: null,
      },
      decimals: 0,
      token_metadata:
        "https://opensea.mypinata.cloud/ipfs/QmWWfomtJkcyVb99KdZR6oza55atifiDPrYkkeSoWah5oe/0",
      owner: {
        user: null,
        profile_img_url:
          "https://storage.googleapis.com/opensea-static/opensea-profile/3.png",
        address: "0x2273beee08c7362ea9df7f5b22b6d43c0d2afccb",
        config: "",
      },
      sell_orders: null,
      creator: null,
      traits: [
        {
          trait_type: "price",
          value: "8",
          display_type: null,
          max_value: null,
          trait_count: 1,
          order: null,
        },
      ],
      last_sale: null,
      top_bid: null,
      listing_date: null,
      is_presale: false,
      transfer_fee_payment_token: null,
      transfer_fee: null,
      token_id: "0",
    },
  ],
};
